# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# OARepo ecosystem is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
# This file was automatically generated by the integration tests to show which changes
# were applied to the package.
"""Changes performed by oarepo-integration-tools."""

# the code below is json, so need to define a couple of aliases just to be sure
true = True
"""JSON True."""

false = False
"""JSON False."""

features_incorporated = '[{"name":"configurable-service-resource","base":"v8.3.0"}]'

oarepo_major_version = "13"

package_oarepo_version = "oarepo-8.3.0"

configuration = '{"name": "invenio-vocabularies", "oarepo": 13, "features": [{"name": "configurable-service-resource", "base": "v8.3.0"}], "package": "invenio-vocabularies", "invenio_version": "8.3.0", "version": "8.3.0"}'
